#!/usr/bin/perl

print("Enter the radius and the circumfernce will be calculated:\n");
chomp($rad = <STDIN>);
$circum = $rad*2*3.14;
print("For a circle with radius $rad, the circumference is $circum.\n");
